# Generated by Django 5.2.7 on 2025-10-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название места', max_length=200, verbose_name='Название места')),
                ('description_short', models.TextField(help_text='Краткое описание места', verbose_name='Краткое описание')),
                ('description_long', models.TextField(help_text='Подробное описание места', verbose_name='Подробное описание')),
                ('latitude', models.FloatField(help_text='Широта в десятичных градусах', verbose_name='Широта')),
                ('longitude', models.FloatField(help_text='Долгота в десятичных градусах', verbose_name='Долгота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['title'],
            },
        ),
    ]
