# Generated by Django 5.2.7 on 2025-10-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение места', null=True, upload_to='places/', verbose_name='Изображение'),
        ),
    ]
