# Generated by Django 5.2.7 on 2025-10-24 09:56

import django.db.models.deletion
import places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение места', null=True, upload_to='places/', validators=[places.models.validate_image_file], verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/photos/', validators=[places.models.validate_image_file], verbose_name='Фотография')),
                ('position', models.PositiveIntegerField(default=1, help_text='Порядок отображения фотографии', verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
