# Generated by Django 5.2.7 on 2025-10-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения фотографии (автоматически)', verbose_name='Позиция'),
        ),
    ]
