# Generated by Django 5.2.7 on 2025-10-24 12:01

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_image_alter_photo_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveIntegerField(default=1, help_text='Группа фотографий для карусели (1, 2, 3...)', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(help_text='Подробное описание места', verbose_name='Подробное описание'),
        ),
    ]
